# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bk < Formula
  desc "Operations layer for beads (bd) — single-binary Go rewrite of beadkeeper."
  homepage "https://github.com/theaichimera/beekeeper-go"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theaichimera/beekeeper-go/releases/download/v0.1.1/beekeeper-go_0.1.1_darwin_x86_64.tar.gz"
      sha256 "b1b29ffe1532a113281a4e696d271ff1b490f809d126f7abb41e38d766bbe93a"

      define_method(:install) do
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theaichimera/beekeeper-go/releases/download/v0.1.1/beekeeper-go_0.1.1_darwin_arm64.tar.gz"
      sha256 "db9bd8fb8c25a9d1c88b7390b0e4cd50029b504e6b838f43d3eb1c3864c9a30a"

      define_method(:install) do
        bin.install "bk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/theaichimera/beekeeper-go/releases/download/v0.1.1/beekeeper-go_0.1.1_linux_x86_64.tar.gz"
      sha256 "f5729a53fed9aef601e0153dbd98d26349ed26dd287035a32b834c160efd0c6e"
      define_method(:install) do
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theaichimera/beekeeper-go/releases/download/v0.1.1/beekeeper-go_0.1.1_linux_arm64.tar.gz"
      sha256 "17b9b36198f278bc0112541019827874aba40cfe19f56878e5503eb72828d78c"
      define_method(:install) do
        bin.install "bk"
      end
    end
  end

  def caveats
    <<~EOS
      bk is the Go port of beadkeeper (Python). Both operate on the same
      .beads/ directory and are interchangeable per-invocation.
      See https://github.com/theaichimera/beekeeper-go#interop-with-python-beadkeeper
    EOS
  end

  test do
    system "#{bin}/bk", "version"
  end
end
